function on_mcm_load()
    op = {
        id = "fireModeCheck",
        sh = true,
        gr = {
            -- LuaFormatter off
            { id = "title", type = "slide", link = "ui_options_slider_player", text = "ui_mcm_fireModeCheck_title", size = {512, 50}, spacing = 20 },
            { id = "userMode", type = "radio_v", val = 2, def = 3, content = { {0, "disabled"}, {1, "basic"}, {2, "dual_key"}, {3, "single_key"} } }
            -- LuaFormatter on
        }
    }
    return op
end

